### ISSUE TITLE
Use on another dataset

### ISSUE THREAD

**Issue by poornimajd** [ram-lab/plycal#1]
Hello 
Great work @liaoqinghai and team!
I am trying to use your work to calibrate the below image from the IDD dataset.
![1](https://user-images.githubusercontent.com/31023599/79832013-2540fa00-83c6-11ea-98f2-f53c965c2181.jpg)

Can I just take any four points in the image which form a rectangle in 3d as my calibration points?
I have images and the corresponding lidar point cloud.
Also I wanted to ask as to what exactly do these X,Y,Z in the given gui correspond to?
Are they the rotation in X,Y,Z direction in radians?
![toshow](https://user-images.githubusercontent.com/31023599/79832428-0b53e700-83c7-11ea-9964-eff5780fbc75.png)

**Comment by liaoqinghai** [comment]
Hi, currently it doesn't support arbitrary rectangle in the dataset, it's recommanded to use some single color flat rectangle board. Since we use the edlines to extract the edge from 2d image where the four points give the hint.
In the above image, the 6 slide bar is used to help set the initial extrinsic parameter, when you manipulate the slidar, you can see the image is projected to pointcloud and pointcloud is also projected to image. The program needs a good initial paramere which is set by human via above window.

**Comment by poornimajd** [comment]
Thank you for the detailed reply.I wanted to know as to how do you evaluate the accuracy of these lidar lines projected onto the image.
![Screenshot from 2020-04-22 08-46-41](https://user-images.githubusercontent.com/31023599/80858616-f05f5d80-8c77-11ea-867c-d10966d0c641.png)
Can these be considered as isolines having same color at a particular distance from the camera?
Thankyou
