### ISSUE TITLE
Hi, I tried this ans use your data, but when I push the button 'Calibrate', Segment Fault happened, can you give me some advice? Thank you!

### ISSUE THREAD

**Issue by bigtongclimb** [ram-lab/plycal#8]

**Comment by oliteksamuelfogarty** [comment]
I was experiencing my problems from just trying to load the demo data folder - which started by saying 'Segment Fault', but as I added lines for debugging changed to 'stack smashing detected'. Lots of commenting out code and things, and it looks like the problem is that some functions report having a return value in the function header, but don't necessarily actually return any value. 
When running the make you may get warnings about the lack of return values - I would try fixing all those up.

**Comment by bigtongclimb** [comment]
Okok, thank you!

**Comment by chengguizi** [comment]
Hi @oliteksamuelfogarty , did you manage to solve your `seg fault` problem yet? I am also having the same issue opening the data folder.

**Comment by oliteksamuelfogarty** [comment]
I was using Ubuntu 20, and didn't figure out the problems. I guess I should have tried 18.

**Comment by bigtongclimb** [comment]
I use Ubuntu18, and somtimes it did not work, and sometimes it worked, so I think you can try more times



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年06月07日 06:39 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [ram-lab/plycal] Hi, I tried this ans use your data, but when I push the button 'Calibrate', Segment Fault happened, can you give me some advice? Thank you! (Issue #8) |

I was using Ubuntu 20, and didn't figure out the problems. I guess I should have tried 18.
